# Generated by Django 5.1.2 on 2024-10-25 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assetsliabilities',
            table='AssetsLiabilities',
        ),
        migrations.AlterModelTable(
            name='budget',
            table='Budget',
        ),
        migrations.AlterModelTable(
            name='cashflow',
            table='CashFlow',
        ),
        migrations.AlterModelTable(
            name='debt',
            table='Debt',
        ),
        migrations.AlterModelTable(
            name='expenses',
            table='Expenses',
        ),
        migrations.AlterModelTable(
            name='financialreports',
            table='FinancialReports',
        ),
        migrations.AlterModelTable(
            name='funding',
            table='Funding',
        ),
        migrations.AlterModelTable(
            name='investments',
            table='Investments',
        ),
        migrations.AlterModelTable(
            name='profit',
            table='Profit',
        ),
        migrations.AlterModelTable(
            name='revenue',
            table='Revenue',
        ),
    ]
