# Generated by Django 5.1.2 on 2024-10-24 14:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_session_title'),
        ('users', '0003_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordmessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='recordmessage',
            name='session',
        ),
        migrations.RemoveField(
            model_name='session',
            name='patient',
        ),
        migrations.CreateModel(
            name='BillType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('assets', 'assets'), ('liabilities', 'liabilities')], max_length=64)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='price of unit')),
                ('quantity', models.IntegerField(verbose_name='quantity on the bill')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='messaging.billtype')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('recommandation', models.TextField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('format_type', models.CharField(max_length=64)),
                ('picture', models.ImageField(upload_to='media/reports/')),
                ('description', models.TextField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization')),
            ],
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='RecordMessage',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
