# Generated by Django 5.1.2 on 2024-10-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0009_remove_recordmessage_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialinsight',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
