# Generated by Django 5.1.2 on 2024-10-24 14:41

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='capital',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='started with capital'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='debt',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='now debt'),
        ),
    ]
